### ISSUE TITLE
Error on harvest!

### ISSUE THREAD

**Issue by luckie12** [justbetter/statamic-feedback-company#5]
Hi!

I followed everything to use this addon, but as soon as i type 

`php artisan reviews:harvest` i get 

`  range(): Argument #3 ($step) must not exceed the specified range`

i went in your code and changed line 85 on HarvestReviews.php 

from 
        `    foreach (range($pageSize, $total, $pageSize) as $page) {`
to
`     foreach (range($pageSize, $total, 1) as $page) {`

as test, and this worked... But when i update or composer install these changes are gone ofcourse. So i would like to know if this is my fault or fixable by you :P

the debug values for $pageSize, $total, $pageSize are
100, 9, 100

Thanks in advance!

**Comment by royduin** [comment]
@Jade-GG, do you have time to check this?

**Comment by luckie12** [comment]
Bedankt!
